<a href="https://colab.research.google.com/github/bakhtkhan123/Deep-Learning-BWF-BakhtUllah/blob/main/Task10/Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Numpy array



In [2]:
import numpy as np

In [3]:
arr_1d = np.array([2,4,1,6,7])
arr_1d

array([2, 4, 1, 6, 7])

In [4]:
arr_2d=np.array([[3,2,6],[4,6,3]])
arr_2d

array([[3, 2, 6],
       [4, 6, 3]])

In [5]:
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# Checking dimension of the arrays

In [6]:
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)


1
2
3


In [7]:
arr=np.array([3,2,1,6,7,4,5],ndmin=3) # setting dimension of the array
arr

array([[[3, 2, 1, 6, 7, 4, 5]]])

# Slicing of the *array*





In [8]:
print(arr_1d[1]) #print first element of the array 1
print(arr_1d[-1])#print the last element of the array
print(arr_2d[1,-1])#print the last element of the array


4
7
3


In [9]:
print(arr_1d[1:4])# printing from 2 to 4th value
print(arr_1d[1::3]) # jump of three

[4 1 6]
[4 7]


In [10]:
print(arr_1d.shape)
print(arr_2d.dtype)
print(arr_2d.copy())
print(arr_1d.view())
print(arr_1d.astype('S'))


(5,)
int64
[[3 2 6]
 [4 6 3]]
[2 4 1 6 7]
[b'2' b'4' b'1' b'6' b'7']


# perform Arithematic operation on arrays

In [12]:
arr1=np.array([2,4,6])
arr2=np.array([6,7,8])

sum=arr1+arr2
sub=arr1-arr_2d
mul=arr1*arr2
power=arr1**arr2
print(f"sum is = {sum} \n sub is = {sub} \n mul is = {mul} \n and power is ={power}")

sum is = [ 8 11 14] 
 sub is = [[-1  2  0]
 [-2 -2  3]] 
 mul is = [12 28 48] 
 and power is =[     64   16384 1679616]


In [13]:
mode= arr1%arr2
mode

array([2, 4, 6])

In [18]:
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.power(arr1,arr2))
print(np.divide(arr1,arr2))

[ 8 11 14]
[-4 -3 -2]
[12 28 48]
[     64   16384 1679616]
[0.33333333 0.57142857 0.75      ]
