<a href="https://colab.research.google.com/github/bakhtkhan123/Deep-Learning-BWF-BakhtUllah/blob/main/Task11/LA_and_stat_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra with numpy


In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,3,5,7,9])
arr3=np.random.randint(5,size=(3,3))

In [3]:
arr1,arr2,arr3

(array([1, 2, 3, 4, 5]),
 array([1, 3, 5, 7, 9]),
 array([[3, 0, 1],
        [3, 2, 0],
        [3, 3, 3]]))

In [4]:
vector_multiplication=arr1*2
vector_multiplication

array([ 2,  4,  6,  8, 10])

In [5]:
dot_product=np.dot(arr1,arr2)
dot_product

95

In [6]:
vector_product=np.vdot(arr1,arr2)
vector_product

95

In [7]:
arr3.T # taking transpose

array([[3, 3, 3],
       [0, 2, 3],
       [1, 0, 3]])

In [8]:
arr3

array([[3, 0, 1],
       [3, 2, 0],
       [3, 3, 3]])

In [9]:
arr3[0]# first row

array([3, 0, 1])

In [10]:
arr3[1,1]# second row second column

2

In [11]:
arr3[:,0]# first column

array([3, 3, 3])

In [12]:
np.linalg.det(arr3) # taking determinant

21.0

In [13]:
np.linalg.matrix_rank(arr3)#rank of a matrix

3

In [14]:
np.linalg.eig(arr3) # find eigen value

(array([5.37969751+0.j        , 1.31015125+1.47887421j,
        1.31015125-1.47887421j]),
 array([[-0.3663498 +0.j        , -0.24515364-0.21454666j,
         -0.24515364+0.21454666j],
        [-0.32519165+0.j        , -0.16692166+0.57517511j,
         -0.16692166-0.57517511j],
        [-0.87180171+0.j        ,  0.7315601 +0.j        ,
          0.7315601 -0.j        ]]))

In [15]:
np.matmul(arr1,arr2)

95

In [16]:
I=np.identity(3,dtype='int')# generating identity metrix
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
np.zeros(arr1)

array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]])

In [18]:
np.matmul(arr3,I)# matrix multiply with identity matrix

array([[3, 0, 1],
       [3, 2, 0],
       [3, 3, 3]])

In [19]:
np.linalg.inv(arr3)

array([[ 0.28571429,  0.14285714, -0.0952381 ],
       [-0.42857143,  0.28571429,  0.14285714],
       [ 0.14285714, -0.42857143,  0.28571429]])

# statistic function with numpy

In [42]:
print("Q1 quantile",np.quantile(arr3,.25,1))
print("Q2 quantile",np.quantile(arr3,.50,1))
print("Q3 quantile",np.quantile(arr3,.75,1))

Q1 quantile [0.5 1.  3. ]
Q2 quantile [1. 2. 3.]
Q3 quantile [2.  2.5 3. ]


In [31]:
print("100th percentile",np.percentile(arr2,100))
print("25th percentile",np.percentile(arr2,25))
print("50th percentile",np.percentile(arr2,50))
print("75th percentile",np.percentile(arr2,75))

100th percentile 9.0
25th percentile 3.0
50th percentile 5.0
75th percentile 7.0


In [37]:
np.mean(arr2)

5.0

In [33]:
np.median(arr2)

5.0

In [39]:
import statistics as stat

In [40]:
stat.mode(arr2)

1

In [41]:
np.invert(arr3)

array([[-4, -1, -2],
       [-4, -3, -1],
       [-4, -4, -4]])

In [44]:
stat.stdev(arr2)

3.1622776601683795

In [47]:
np.ceil(arr2)
np.floor(arr1)

array([1., 2., 3., 4., 5.])