<a href="https://colab.research.google.com/github/bakhtkhan123/Deep-Learning-BWF-BakhtUllah/blob/main/Task12/Broadcasting_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadcasting



In [ ]:
import numpy as np

In [ ]:
arr=np.arange(5)
x=arr*2
print(x)
x.shape

[0 2 4 6 8]


(5,)

### broadcast over axis 0 with 1D array

In [ ]:
arr1=np.random.randn(4,3)
print(arr1,'\n')
mean=arr1.mean(0)
print(mean)
print(mean.shape)
print(arr1.shape)

[[ 0.51031093  0.85271275  0.27160314]
 [-1.50205252  1.28805798  0.14143944]
 [ 0.10506771 -0.10008366 -1.39490258]
 [ 0.31426484 -0.9377405   0.13346281]] 

[-0.14310226  0.27573664 -0.2120993 ]
(3,)
(4, 3)


In [ ]:
demean= arr1-mean
print(demean,'\n')
print(demean.mean(0))


[[ 0.82197026  0.01376313 -0.07646105]
 [ 0.8070711   0.27477736 -1.0483038 ]
 [-0.3001473   0.15960774  0.69742089]
 [-1.32889406 -0.44814822  0.42734396]] 

[-5.55111512e-17  0.00000000e+00  1.38777878e-17]


### broadcasting over axis 1 with 1D array

In [ ]:
row_means=arr1.mean(1)
print(row_means)
print(row_means.shape)
print(row_means.reshape(4,1),'\n')
demean=arr-row_means.reshape(4,1)
print(demean,'\n')
print(demean.mean(1))

[ 0.54487561 -0.02418503 -0.46330618 -0.16333761]
(4,)
[[ 0.54487561]
 [-0.02418503]
 [-0.46330618]
 [-0.16333761]] 

[[-0.54487561  0.45512439  1.45512439  2.45512439  3.45512439]
 [ 0.02418503  1.02418503  2.02418503  3.02418503  4.02418503]
 [ 0.46330618  1.46330618  2.46330618  3.46330618  4.46330618]
 [ 0.16333761  1.16333761  2.16333761  3.16333761  4.16333761]] 

[1.45512439 2.02418503 2.46330618 2.16333761]


### broadcasting over other axis

In [ ]:
#arr1-arr1.mean(1)
arr1-arr1.mean(1).reshape(4,1)

array([[-0.03456467,  0.30783714, -0.27327247],
       [-1.47786748,  1.31224301,  0.16562447],
       [ 0.56837389,  0.36322251, -0.9315964 ],
       [ 0.47760246, -0.77440289,  0.29680043]])

In [43]:
arr=np.zeros((4,4))
print(arr,'\n')
arr_3d=arr[:,np.newaxis,:]
print(arr_3d,'\n')
print(arr_3d.shape)

arr_1d=np.random.normal(size=4)
print(arr_1d,'\n')
print(arr_1d[:,np.newaxis],'\n')
print(arr_1d[np.newaxis,:])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]] 

(4, 1, 4)
[-0.39175313  0.789089    0.41162063 -0.22284879] 

[[-0.39175313]
 [ 0.789089  ]
 [ 0.41162063]
 [-0.22284879]] 

[[-0.39175313  0.789089    0.41162063 -0.22284879]]


### setting array values by broadcasting

In [52]:
arr=np.zeros((4,3))
arr[:]=5
print(arr)
col=np.array([1.22,-0.43,.98,1.76])
print('\n',col)
arr[:]=col[:,np.newaxis]
print('\n',arr)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

 [ 1.22 -0.43  0.98  1.76]

 [[ 1.22  1.22  1.22]
 [-0.43 -0.43 -0.43]
 [ 0.98  0.98  0.98]
 [ 1.76  1.76  1.76]]
